authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h #默认 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
# 搜索空间文件
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
# 运行的命令，以及 Trial 代码的路径
trial:
  command: python mnist.py
  codeDir: .
  gpuNum: 0 #默认 0
